# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

build_regression_tree_baysian <- function(X, Y, max_partition_level, cor_cutoff, min_divide_size) {
    .Call('_GNET2_build_regression_tree_baysian', PACKAGE = 'GNET2', X, Y, max_partition_level, cor_cutoff, min_divide_size)
}

