# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pearsoncoeff <- function(X, Y) {
    .Call('_GNET2_pearsoncoeff', PACKAGE = 'GNET2', X, Y)
}

rowwise_avg_cor <- function(Y, row_slt) {
    .Call('_GNET2_rowwise_avg_cor', PACKAGE = 'GNET2', Y, row_slt)
}

update_score <- function(X, left_idx_bool, right_idx_bool) {
    .Call('_GNET2_update_score', PACKAGE = 'GNET2', X, left_idx_bool, right_idx_bool)
}

find_new_split <- function(X, Y, groups, feature_remaining) {
    .Call('_GNET2_find_new_split', PACKAGE = 'GNET2', X, Y, groups, feature_remaining)
}

build_regression_tree_baysian <- function(X, Y, max_partition_level, cor_cutoff, min_divide_size) {
    .Call('_GNET2_build_regression_tree_baysian', PACKAGE = 'GNET2', X, Y, max_partition_level, cor_cutoff, min_divide_size)
}

